ticket 11 complete
Pink-Flag/be-project pull request #10
Opened 2022-05-19 13:48 UTC by Pink-Flag

2022-05-19 14:33 UTC, elijaharley requested changes
Some really nice logic here Matthew, just a couple of recommendations in the comments

2022-05-19 14:33 UTC, elijaharley commented on Controllers/articlesController.js
>      })
Nice solution with greenlisting here to check that the query is allowed, however I'd recommend consistency in the models and controllers where errors are only thrown from one or the other. I think your other errors are being thrown from the model so I'd move this logic there. I'd suggest greenlisting valid topics using this method in the model too, to avoid SQL injection.

2022-05-19 14:33 UTC, elijaharley commented on __tests__/app.test.js
> +});
Good testing here - just a few cases that will need to be tested - 

 Status 200, array of article objects (including comment_count, excluding body) <-- just need to ass an objectContaining to this test.
 Status 400. invalid sort_by query, e.g. ?sort_by=fugazi <-----should be 400 not 404
 Status 404. non-existent topic query, e.g. ?topic=bananas
 Status 200. valid topic query, but has no articles responds with an empty array of articles, e.g. ?topic=paper

2022-05-20 08:02 UTC, Pink-Flag commented
added new tests and refactored to move error handling and greenlisting to model

2022-05-20 08:28 UTC, dappernerddesigns approved these changes
Good updates. Nice work, merge when ready :)

2022-05-20 08:29 UTC, merged